[package]
name = "ub_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
revm-interpreter = {git = "https://github.com/wtdcode/revm", branch = "ub"}
revm-primitives = {git = "https://github.com/wtdcode/revm", branch = "ub"}